### PR TITLE
Added ability to configure jira specific options in config.yml

### LINKED ISSUE #3: Self-signed certs trigger SSL error
I'm trying to access a JIRA instance that has a self-signed certificate.  I get the following error: `WARNING:root:Got recoverable error from GET https://jira.nap/rest/api/2/serverInfo, will retry [1/3] in 10s. Err: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)`

Would it be possible to add a CLI switch to ignore SSL certificate errors?

### PR DESCRIPTION
**Pull request by MrReasonable**
This PR resolves #3 by allowing the user to set `verify: false` in the config file.

### CODE REVIEW

**Comment by MrReasonable** [comment]
@optilude Anything need to doing to this PR for you to accept it?

**Comment by optilude** [comment]
Sorry (and hi!) I didn't see this before.

No real issue with the code but what's the has case for this?

I think calling the option `JIRA` is a bit confusing. Maybe something more descriptive?

**Comment by MrReasonable** [comment]
Hiya!  The need for this came up where I'm currently working.  They use an installed JIRA instance that has self-signed certificates.  The application failed with an error message about rejecting the self-signed cert (see #3).

I named the option JIRA because, well, it is a list of options passed directly to the Python JIRA library.  I'm not sure what else to name the config, any suggestions?

**Comment by optilude** [comment]
How about `jira-client-options` to be explicit?

**Comment by MrReasonable** [comment]
I've renamed the jira client options as per your suggestion.  Any other things that need changing?

**Pull request merged**
